Repository kubernetes-sigs/downloadkubernetes, pull requests merged in 2020-09, with the labels that each got.

#9 Cleanup go modules and switch to go1.15
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/L

#11 Update node dependencies and add update script
  dist/css/main.bundle.css
  dist/js/bundle.js
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#13 small refactor in the versions part to use semver
  .gitignore
  cmd/update-index/main.go
  dist/index.html
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#15 Update for Kubernetes v1.19.1
  dist/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XL
