Repository kubernetes-sigs/downloadkubernetes, pull requests merged in 2023-05, with the labels that each got.

#437 fix: add footer with kubernetes resources
  cmd/update-index/data/index.html.template
  cmd/update-index/main.go
  dist/index.html
Labels: kind/feature, approved, size/L, cncf-cla: yes, lgtm, sig/release

#440 Upgrade go to 1.20, dependabot config and github actions updates
  .github/dependabot.yml
  .github/workflows/update-index.yml
  .golangci.yml
  cmd/update-index/main.go
  go.mod
  go.sum
  hack/verify-golangci-lint.sh
Labels: approved, size/M, cncf-cla: yes, lgtm, sig/release

#441 feat: Add centered buttons and self-contained table scrolling
  cmd/update-index/data/index.html.template
  dist/index.html
  src/mystyles.scss
Labels: approved, cncf-cla: yes, lgtm, sig/release, size/XXL
